apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  selector:
    matchLabels:
      app: go-server
  replicas: 1
  template:
    metadata:
      name: "go-server"
      labels:
        app: "go-server"
    spec:
      containers:
        - name: go-server
          image: "tiagolorenzetti/hello-go:v5.5"

          resources:
            requests:
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi
            
          startupProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 3
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 1
            failureThreshold: 1
            
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
            
          envFrom:
            - configMapRef:
                name: go-server-env
            - secretRef:
                name: go-server-secret

          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true
            - mountPath: "/go/pvc"
              name: go-server-volume

      volumes:
        - name: go-server-volume
          persistentVolumeClaim:
            claimName: go-server-pvc

        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"
        
