apiVersion: v1
kind: Service
metadata:
  name: go-server-service
spec:
  selector:
    app: go-server
  type: LoadBalancer
  ports:
  - name: go-server-service
    port: 8090
    targetPort: 8081
    protocol: TCP